name: "Execute Kotlin Script"
description: "Run the Kotlin Script with a compiler plugin"
author: Suresh
branding:
  color: gray-dark
  icon: package

inputs:
  script: # Kotlin script file
    description: 'Kotlin script to execute'
    required: true
    default: 'script.main.kts'
  compiler-plugin:
    description: 'Kotlin compiler plugin to use (kotlinx-serialization|allopen|noarg|lombok|sam-with-receiver)'
    required: false
    default: 'kotlinx-serialization'

outputs:
  plugin-path:
    description: "Kotlin compiler plugin jar path"
    value: ${{ steps.kotlin-plugin.outputs.plugin-path }}

runs:
  using: "composite"
  steps:
    - name: Get the Kotlin compiler plugin jar for ${{ inputs.compiler-plugin }}
      id: kotlin-plugin
      run: $GITHUB_ACTION_PATH/kotlin-plugin.sh ${{ inputs.compiler-plugin }}
      shell: bash

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
        key: ${{ runner.os }}-ivy-${{ hashFiles(${{ inputs.script }}) }}
        restore-keys: |
          ${{ runner.os }}-ivy-

    - name: Run kotlin script ${{ inputs.script }}
      run: kotlinc -script -Xplugin=${{ steps.kotlin-plugin.outputs.plugin-path }} ${{ inputs.script }}
      shell: bash