name: Kotlin Script Test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash


jobs:
  kts-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run Kotlin Script on ${{ matrix.os }}
        id: kotlin-script-exec
        uses: ./
        with:
          script: ".github/scripts/script.main.kts"
          compiler-plugin: kotlinx-serialization

      - name: Print compiler plugin path
        run: |
          java -version
          echo ${{ steps.kotlin-script-exec.outputs.plugin-path }}
